version: '3.8'

services:

  soonsolve:
      build: 
        context: .
        dockerfile: Dockerfile
      container_name: ss_container
      volumes:
        - userImage:/soonsolve/static
      networks:
        - ss_network

  # redis:
  #   # image: redis:6.0.16
  #   # container_name: redis
  #   # restart: always
  #   # networks:
  #   #   - ss_network
  rabbitmq:
    image: "rabbitmq:latest"
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ 使用的通訊埠
      - "15672:15672"  # RabbitMQ 管理界面的通訊埠
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: soonsolve
    # volumes:
    #   - rabbitMQ:/var/lib/rabbitmq/mnesia 
    networks:
      - ss_network  
  nginx:
    image: nginx:1.18.0
    container_name: nginx
    # restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
      - ./private/certificate.crt:/etc/ssl/certificate.crt  # 替換為您的 SSL 證書路徑
      - ./private/private.key:/etc/ssl/private.key  # 替換為 SSL 私鑰的路徑
    networks:
      - ss_network  
    depends_on:
      - soonsolve

volumes:
  userImage:
  # rabbitMQ:

networks:
  ss_network:   
