version: '3.8'

services:

  redis:
    # image: redis:6.0.16
    # container_name: redis
    # restart: always
    # networks:
    #   - ss_network

  nginx:
    image: nginx:1.18.0
    container_name: nginx
    # restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
      - ./private/certificate.crt:/etc/ssl/certificate.crt  # 替換為您的 SSL 證書路徑
      - ./private/private.key:/etc/ssl/private.key  # 替換為 SSL 私鑰的路徑
    networks:
      - ss_network  

networks:
  ss_network:   
